name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs }}"
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
          
      - name: KUBECTL apply
        run: |
          chmod +x script.sh
          ./script.sh
        shell: bash
  #      run: |
  #        echo "All"
  #        echo "${{ steps.abc.outputs }}"
  #      if: ${{ endswith(${{steps.abc.outputs.added}}, 'yml') }}
